#!/bin/bash
set -eo pipefail

root="$(dirname $0)"
pkg="$root/packages/sqrl-cli"

$root/scripts/ensure-installed

export NODE_PATH="$pkg/node_modules:$NODE_PATH"

# We could use ts-node, however it would use the compiled code from everything
# but the `sqrl-cli` project which is rather confusing. Instead just use all
# compiled code only, which makes it clear that you need to `npm run build` in
# order to see changes you've made.

exec node --max-old-space-size=4096 \
          "$pkg/bin/cli.js" "$@"
