#!/bin/bash

root="$(dirname $0)"
pkg="$root/packages/sqrl"

$root/scripts/ensure-installed

export NODE_PATH="$pkg/node_modules:$NODE_PATH"
exec node --require ts-node/register \
          --max-old-space-size=4096 \
          "$pkg/src/cli.ts" "$@"
