#!/bin/bash
set -eo pipefail

root="$(dirname $0)/.."
pkg="$root/packages/sqrl"

if [ ! -e "$root/node_modules" ]; then
  echo 'Core dependencies not found!' >&2
  echo 'Please run `npm install && npm run bootstrap` first.' >&2
  exit 1
fi

if [ ! -e "$pkg/node_modules" ]; then
  echo 'SQRL package dependencies not found!' >&2
  echo 'Please run `npm run bootstrap` first.' >&2
  exit 1
fi
