#!/bin/bash
set -eo pipefail

cd "$(dirname $0)/../.."
./scripts/ensure-installed

node tools/wikipedia-diff-stream/main.js en.wikipedia.org | \
  ./sqrl run ./examples/wikipedia/main.sqrl --stream=EventData "$@"
